### PR TITLE
v0.8.0: Move/Copy improvements, removed path, improved names, new interfaces / extension methods

### LINKED ISSUE #9: Improvements to Copy / Move operations
# Background 
### Minimum end goal
Without sacrificing potential functionality or performance, we should strive to:

1. **Maximize compatibility** - with as many file systems as reasonably possible
2. **Minimize effort** - for implementors, consumers and maintainers.

### Specification
- Create the minimal possible interface for files/folders (the "starting point")
- Additional capabilities beyond basics should be done using derived interfaces (see examples below)
  - As separate interfaces, new APIs break nothing. As a derived interface, implementations work with existing code.
  - Breaking changes will affect as few implementations as possible
  - Determining lack of support by checking `if (instance is IMyThing thing)` is faster and more natural than catching thrown `NotSupportException`s.
- Implementors only need to implement what they can do, no more or less.
- Consumers only ask for what's needed, no more or less. Simply ask (or check) for that interface.
- We should have an inbox fallback implementation for certain things (like copy/move) that can work across different file systems.
    - This allows us to align the majority of cross-storage implementations without requiring a base class
    - Removes the need for everyone to do their own implementation
    - Allows for a more performant version if present.
- We should consider file/folder implementations that differ from traditional on-disk systems (e.g. blob storage, mocked files)

# The problem
In the current version of [`IModifiableFolder`](https://github.com/Arlodotexe/OwlCore.Storage/blob/fd5bb8f689f50b42b2a57ed30e29ec53477584dc/src/IModifiableFolder.cs), `CreateCopyOfAsync` and `MoveFromAsync` are _required_ to be implemented by the consumer.

Our interfaces need to represent the minimum possible concept of a file system, and extended using the extension method + fastpath interface tactic mentioned above.

We only _need_ implementors to implement creation and deletion. Using those 2 things, we can build generic "Copy" and "Move" extension methods, and add these 2 methods to a fastpath interface.

# The solution
- [ ] Move CreateCopyOfAsync and MoveFromAsync into a separate interface (the new fastpath interface)
- [ ] Create extension methods for CreateCopyOfAsync and MoveFromAsync that check for fastpath interfaces, and when not present use the create and delete methods on  to copy and move between file systems.
- [ ] Investigate adding an overload/fastpath for copying/moving folders.

### LINKED ISSUE #17: Rename IStorageProperties<T> to IStorageProperty<T>
The interface `IStorageProperties<T>` represents a single storage property, and thus should be renamed to `IStorageProperty<T>`

### LINKED ISSUE #18: Remove Path and rename IAddressable*
On [Discord](https://discord.com/channels/372137812037730304/1019645710750199848/1061772063934775326
) in the [UWP Community](https://uwpcommunity.com/), `d2dyno#5600` has suggested to rename `IAddressable` to `ILocatable`.

This issue serves as discussion and planning for the suggestion.

---

Update: Rather than a simple rename, we've effectively scrapped the interface and tried again with new hindsight. Tl;dr -> https://github.com/Arlodotexe/OwlCore.Storage/issues/18#issuecomment-1420164727

### PR DESCRIPTION
**Pull request by Arlodotexe**
### Summary
- Closes #18
- Closes #17 
- Closes #9 
- Renames several interfaces using feedback from @yoshiask and d2d1 from the UWP Community.
- Adds several new extension methods to to substitute any functionality gaps that removing Path has caused.

### Full release notes
```
--- 0.8.0 ---
THIS IS A BREAKING RELEASE
Update asap, and do not use older versions or implementations.

[Breaking]
Path was removed from IAddressableStorable. This was not spec'd or standardized, and simply exposed the "path" used by the underlying implementation, so we removed it. Additional tooling has been added to substitute any functionality gaps that removing this has caused.
Renamed IStorageProperties{T} to IStorageProperty{T}.
Renamed IAddressableStorable to IStorableChild, as the only thing on the interface is now GetParentAsync.
Renamed IAddressableFolder to IChildFolder.
Renamed IAddressableFile to IChildFile.
Renamed IFolderCanFastGetItem to IFastGetItem.
Renamed IFolderCanFastGetFirstItemByName to IFastGetFirstByName.
Renamed the extension method GetFirstItemByNameAsync to GetFirstByNameAsync.
IModifiableFolder no longer requires implementing copy/move operations. Please remove from your implementations, and implement the fastpath interfaces where appropriate.
HttpFile's constructor now only has 1 parameter - the Uri.
HttpFile has a new constructor that takes a string instead of a Uri, for convenience.
HttpFile.Name now has an init-only setter.
HttpFile.Id is no longer customizable, and is always created from the provided Uri instead.

[New]
Added IFastGetRoot interface.
Added IFastFileCopy{T} interface.
Added IFastFileMove{T} interface.
Added IFastGetItemRecursive interface.
Added GetRootAsync extension method.
Added ModifiableFolderExtensions.CreateCopyOfAsync{T} extension method.
Added ModifiableFolderExtensions.MoveFromAsync{T} extension method.
Added FolderExtensions.GetItemRecursiveAsync extension method.
Added FolderExtensions.GetRelativePathToAsync extension method, to generate a relative path from one item to another.
Added FolderExtensions.GetItemByRelativePathAsync extension method, to traverse a relative path from one item to another.
Added FolderExtensions.GetItemRecursiveAsync extension method, to recursively search a folder for an item with the provided ID.
SystemFolder now implements IFastGetRoot.
ZipArchiveFolder now implements IFastGetRoot.
ReadOnlyZipArchiveFolder now implements IFastGetRoot.
```

### CODE REVIEW

File: src/Archive/ReadOnlyZipArchiveFolder.cs [hunk 1]
```diff
@@ -14,7 +14,7 @@ namespace OwlCore.Storage.Archive;
 /// A folder implementation wrapping a <see cref="ZipArchive"/> with
 /// mode <see cref="ZipArchiveMode.Read"/> or <see cref="ZipArchiveMode.Update"/>.
 /// </summary>
-public class ReadOnlyZipArchiveFolder : IAddressableFolder, IDisposable
+public class ReadOnlyZipArchiveFolder : IChildFolder, IFastGetRoot, IFastGetItem, IFastGetFirstByName, IDisposable
```
Comment (amaid) [inline src/Archive/ReadOnlyZipArchiveFolder.cs:17]: Looks like the names of the interfaces are verbs, ideally they should be nouns

File: src/Archive/ReadOnlyZipArchiveFolder.cs [hunk 2]
```diff
@@ -140,13 +140,47 @@ public async IAsyncEnumerable<IAddressableStorable> GetItemsAsync(StorableType t
         }
     }
 
+    /// <inheritdoc/>
+    public async Task<IStorableChild> GetItemAsync(string id, CancellationToken cancellationToken = default)
+    {
+        cancellationToken.ThrowIfCancellationRequested();
```
Comment (amaid) [inline src/Archive/ReadOnlyZipArchiveFolder.cs:146]: Why not safely return if the TaskCancellation is requested using the `IsCancellationRequested` flag?

File: src/Archive/ZipArchiveFolder.cs [hunk 3]
```diff
@@ -136,11 +107,13 @@ public async Task DeleteAsync(IAddressableStorable item, CancellationToken cance
 
             GetVirtualFolders().Remove(folder.Id);
         }
-        else
+        else if (item is ReadOnlyZipArchiveFolder readOnlyFolder)
         {
-            var entry = TryGetEntry(item.Path);
+            var entry = TryGetEntry(readOnlyFolder.Path);
             entry?.Delete();
```
Comment (amaid) [inline src/Archive/ZipArchiveFolder.cs:113]: No async overload available for deletion?

File: src/Archive/ZipArchiveFolder.cs [hunk 4]
```diff
@@ -136,11 +107,13 @@ public async Task DeleteAsync(IAddressableStorable item, CancellationToken cance
...
         }
+
+        throw new FileNotFoundException("The item was not found in the folder.");
```
Comment (amaid) [inline src/Archive/ZipArchiveFolder.cs:116]: Are you throwing unconditionally?

File: src/Extensions/CopyAndMoveExtensions.cs [hunk 5]
```diff
@@ -0,0 +1,67 @@
...
+    /// </summary>
+    /// <param name="destinationFolder">The folder where the copy is created.</param>
+    /// <param name="fileToCopy">The file to be copied into this folder.</param>
+    /// <param name="overwrite"><code>true</code> if the destination file can be overwritten; otherwise, <c>false</c>.</param>
+    /// <param name="cancellationToken">The cancellation token to observe.</param>
+    public static async Task<IChildFile> CreateCopyOfAsync<T>(this IModifiableFolder destinationFolder, T fileToCopy, bool overwrite = default, CancellationToken cancellationToken = default)
+        where T : IFile
+    {
+        // If the destination folder can copy this file faster than us, use that.
+        if (destinationFolder is IFastFileCopy<T> fastPath)
```
Comment (amaid) [inline src/Extensions/CopyAndMoveExtensions.cs:23]: How can a folder also be a FastFile? 
`// If the destination folder can copy this file faster than us, use that.`
What does copy faster means here?

File: src/Extensions/CopyAndMoveExtensions.cs [hunk 6]
```diff
@@ -0,0 +1,67 @@
...
+
+        // Align stream positions (if possible)
+        if (destinationStream.CanSeek && destinationStream.Position != 0)
+            destinationStream.Seek(0, SeekOrigin.Begin);
+
+        if (sourceStream.CanSeek && sourceStream.Position != 0)
+            sourceStream.Seek(0, SeekOrigin.Begin);
+
+        // Copy the src into the dest file
+        await sourceStream.CopyToAsync(destinationStream, bufferSize: 81920, cancellationToken);
```
Comment (amaid) [inline src/Extensions/CopyAndMoveExtensions.cs:41]: No exception handling here? What if copy failed due to some reason?

File: src/Extensions/CopyAndMoveExtensions.cs [hunk 7]
```diff
@@ -0,0 +1,67 @@
...
+    public static async Task<IChildFile> MoveFromAsync<T>(this IModifiableFolder destinationFolder, T fileToMove, IModifiableFolder source, bool overwrite = default, CancellationToken cancellationToken = default)
+        where T : IFile, IStorableChild
+    {
+        // If the destination folder can move this file faster than us, use that.
+        if (destinationFolder is IFastFileMove<T> fastPath)
+            return await fastPath.MoveFromAsync(fileToMove, source, overwrite, cancellationToken);
+
+        // Manual move. Slower, but covers all scenarios.
+        var file = await destinationFolder.CreateCopyOfAsync(fileToMove, overwrite, cancellationToken);
+        await source.DeleteAsync(fileToMove, cancellationToken);
```
Comment (amaid) [inline src/Extensions/CopyAndMoveExtensions.cs:63]: No exception handling?

File: src/Extensions/GetFilesAndFoldersExtensions.cs [hunk 8]
```diff
@@ -0,0 +1,27 @@
...
+/// </summary>
+public static partial class FolderExtensions
+{
+    /// <summary>
+    /// Retrieves all files from the provided <see cref="IFolder"/>.
+    /// </summary>
+    /// <param name="folder">The folder to get files from.</param>
+    /// <param name="cancellationToken">The cancellation token to observe.</param>
+    /// <returns>An async enumerable which yields the files in the provided folder.</returns>
+    public static IAsyncEnumerable<IChildFile> GetFilesAsync(this IFolder folder, CancellationToken cancellationToken = default) => folder.GetItemsAsync(StorableType.File, cancellationToken).Cast<IChildFile>();
```
Comment (amaid) [inline src/Extensions/GetFilesAndFoldersExtensions.cs:18]: Maybe if the Items count is 0 don't cast it?

File: src/Extensions/GetFilesAndFoldersExtensions.cs [hunk 9]
```diff
@@ -0,0 +1,27 @@
...
+
+    /// <summary>
+    /// Retrieves all files from the provided <see cref="IFolder"/>.
+    /// </summary>
+    /// <param name="folder">The folder to get files from.</param>
+    /// <param name="cancellationToken">The cancellation token to observe.</param>
+    /// <returns>An async enumerable which yields the folders in the provided folder.</returns>
+    public static IAsyncEnumerable<IChildFolder> GetFoldersAsync(this IFolder folder, CancellationToken cancellationToken = default) => folder.GetItemsAsync(StorableType.Folder, cancellationToken).Cast<IChildFolder>();
```
Comment (amaid) [inline src/Extensions/GetFilesAndFoldersExtensions.cs:26]: Maybe if the Items count is 0 don't cast it?

File: src/Extensions/GetFirstByNameExtension.cs [hunk 10]
```diff
@@ -0,0 +1,32 @@
...
+{
+    /// <summary>
+    /// Retrieves the first <see cref="IStorable"/> item which has the provided <paramref name="name"/>.
+    /// </summary>
+    /// <param name="folder">The folder to get items from.</param>
+    /// <param name="name">The <see cref="IStorable.Name"/> of the storable item to retrieve.</param>
+    /// <param name="cancellationToken">The cancellation token to observe.</param>
+    /// <returns>An async enumerable which yields the items in the provided folder.</returns>
+    /// <exception cref="FileNotFoundException">The item was not found in the provided folder.</exception>
+    public static async Task<IStorableChild> GetFirstByNameAsync(this IFolder folder, string name, CancellationToken cancellationToken = default)
```
Comment (amaid) [inline src/Extensions/GetFirstByNameExtension.cs:19]: Maybe rename it to GetFirst`Item`ByName?

File: src/Extensions/GetItemByRelativePathExtension.cs [hunk 11]
```diff
@@ -0,0 +1,74 @@
...
+    /// <param name="cancellationToken">A token to cancel the ongoing operation.</param>
+    /// <returns>The <see cref="IStorable"/> item found at the relative path.</returns>
+    /// <exception cref="ArgumentException">
+    /// A parent directory was specified, but the provided <see cref="IStorable"/> is not addressable.
+    /// Or, the provided relative path named a folder, but the item was a file.
+    /// Or, an empty path part was found.
+    /// </exception>
+    /// <exception cref="ArgumentOutOfRangeException">A parent folder was requested, but the storable item did not return a parent.</exception>
+    /// <exception cref="FileNotFoundException">A named item was specified in a folder, but the item wasn't found.</exception>
+    public static async Task<IStorable> GetItemByRelativePathAsync(this IStorable from, string relativePath, CancellationToken cancellationToken = default)
```
Comment (amaid) [inline src/Extensions/GetItemByRelativePathExtension.cs:28]: Nice one!!

File: src/Extensions/GetRelativePathToExtension.cs [hunk 12]
```diff
@@ -0,0 +1,44 @@
...
+        var pathComponents = new List<string>
+        {
+            to.Name,
+        };
+
+        await RecursiveAddParentToPathAsync(to);
+
+        // Relative path to a folder should end with a directory separator '/'
+        // Relative path to a file should end with the file name.
+        return to switch
```
Comment (amaid) [inline src/Extensions/GetRelativePathToExtension.cs:27]: "Return to switch" that's new?

File: src/HttpFile.cs [hunk 13]
```diff
@@ -15,26 +14,24 @@ public class HttpFile : IFile
...
+    /// Creates a new instance of <see cref="HttpFile"/>.
     /// </summary>
     /// <param name="uri">The http address to GET for the file content.</param>
     public HttpFile(Uri uri)
-        : this(uri, uri.OriginalString, Path.GetFileName(uri.AbsolutePath))
     {
+        Uri = uri;
+        Name = Path.GetFileName(uri.AbsolutePath);
+        Id = uri.OriginalString;
+        MessageHandler = new HttpClientHandler();
```
Comment (amaid) [inline src/HttpFile.cs:25]: This violates Inversion of Control, creation of an instance silently comes under hidden functionality, maybe pass the messageHandler from the constructor?

File: src/Memory/MemoryFolder.cs [hunk 14]
```diff
@@ -133,20 +141,24 @@ public async Task<IAddressableFile> MoveFromAsync(IAddressableFile fileToMove, I
...
+        var existingFolder = existingFolderKvp.Value as IChildFolder;
 
         if (overwrite && existingFolder is not null)
         {
             await DeleteAsync(existingFolder, cancellationToken);
         }
 
-        var emptyMemoryFolder = new AddressableMemoryFolder(name, new IFolder[] { this });
-        var folder = overwrite ? emptyMemoryFolder : (existingFolder ?? emptyMemoryFolder);
+        var emptyMemoryFolder = new MemoryFolder($"{Guid.NewGuid()}", name)
```
Comment (amaid) [inline src/Memory/MemoryFolder.cs:156]: Why MemoryFolder isn't disposable?

File: src/SystemIO/SystemFolder.cs [hunk 15]
```diff
@@ -12,32 +13,35 @@ namespace OwlCore.Storage.SystemIO;
...
     /// <param name="directoryInfo">The directory to use.</param>
     public SystemFolder(DirectoryInfo directoryInfo)
-        : this(directoryInfo.FullName)
     {
+        _directoryInfo = directoryInfo;
+
+        // For consistency, always remove the trailing directory separator.
+        Path = directoryInfo.FullName.TrimEnd(System.IO.Path.PathSeparator, System.IO.Path.DirectorySeparatorChar, System.IO.Path.AltDirectorySeparatorChar);
+
+        if (!Directory.Exists(Path))
```
Comment (amaid) [inline src/SystemIO/SystemFolder.cs:40]: Disk operation in a constructor? Isn't it a bit heavy lifting?

File: src/SystemIO/SystemFolder.cs [hunk 16]
```diff
@@ -12,32 +13,35 @@ namespace OwlCore.Storage.SystemIO;
...
+            throw new FileNotFoundException($"Directory not found at path {Path}");
```
Comment (amaid) [inline src/SystemIO/SystemFolder.cs:41]: Maybe don't throw exception on instance creation?

File: src/SystemIO/SystemFolder.cs [hunk 17]
```diff
@@ -12,32 +13,35 @@ namespace OwlCore.Storage.SystemIO;
...
+
+        Id = Path;
+        Name = System.IO.Path.GetFileName(Path) ?? throw new ArgumentException($"Could not determine directory name from path {Path}");
```
Comment (amaid) [inline src/SystemIO/SystemFolder.cs:44]: Maybe don't throw exception on instance creation?

File: src/SystemIO/SystemFolder.cs [hunk 18]
```diff
@@ -104,19 +108,38 @@ public async IAsyncEnumerable<IAddressableStorable> GetItemsAsync(StorableType t
     }
 
     /// <inheritdoc />
-    public Task<IAddressableStorable> GetItemAsync(string id, CancellationToken cancellationToken = default)
+    public Task<IStorableChild> GetItemRecursiveAsync(string id, CancellationToken cancellationToken = default)
     {
+        if (!id.Contains(Path))
+            throw new FileNotFoundException($"The provided ID does not belong to an item in this folder.");
```
Comment (amaid) [inline src/SystemIO/SystemFolder.cs:114]: Are there any "Storage" related Ids that don't have paths appended? If no maybe just throw "Provided Id is invalid"?

File: src/SystemIO/SystemFolder.cs [hunk 19]
```diff
@@ -144,105 +167,102 @@ public Task<IFolderWatcher> GetFolderWatcherAsync(CancellationToken cancellation
...
 
-        if (IsFolder(item.Path))
-            Directory.Delete(item.Path, recursive: true);
+        if (IsFolder(item.Id))
+            Directory.Delete(item.Id, recursive: true);
 
-        if (IsFile(item.Path))
-            File.Delete(item.Path);
+        if (IsFile(item.Id))
+            File.Delete(item.Id);
```
Comment (amaid) [inline src/SystemIO/SystemFolder.cs:180]: No Async overload available?

File: src/SystemIO/SystemFolder.cs [hunk 20]
```diff
@@ -144,105 +167,102 @@ public Task<IFolderWatcher> GetFolderWatcherAsync(CancellationToken cancellation
...
-                if (!overwrite)
-                    return new SystemFile(newPath);
+            File.Delete(newPath);
+        }
 
-                File.Delete(newPath);
-            }
-            
-            File.Copy(sysFile.Path, newPath, overwrite);
+        File.Copy(fileToCopy.Path, newPath, overwrite);
```
Comment (amaid) [inline src/SystemIO/SystemFolder.cs:202]: No exception handling/throwing here?

File: src/SystemIO/SystemFolder.cs [hunk 21]
```diff
@@ -144,105 +167,102 @@ public Task<IFolderWatcher> GetFolderWatcherAsync(CancellationToken cancellation
...
+            return new SystemFile(newPath);
 
-        if (sourceStream.CanSeek)
-            sourceStream.Seek(0, SeekOrigin.Begin);
+        if (overwrite)
+            File.Delete(newPath);
 
-        using var destinationStream = File.Create(newPath);
-        await sourceStream.CopyToAsync(destinationStream, bufferSize: 81920, cancellationToken);
+        File.Move(fileToMove.Path, newPath);
```
Comment (amaid) [inline src/SystemIO/SystemFolder.cs:218]: No exception handling/throwing here?

**Review by amaid — CHANGES_REQUESTED** [review]

File: src/Archive/ReadOnlyZipArchiveFolder.cs (hunk 1 above)
Comment (Arlodotexe) [reply src/Archive/ReadOnlyZipArchiveFolder.cs:17]: From the [dotnet standard naming guidelines](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-classes-structs-and-interfaces):
> ✔️ DO name classes and structs with nouns or noun phrases, using PascalCasing.
> 
> This distinguishes type names from methods, which are named with verb phrases.
> 
> ✔️ DO name interfaces with adjective phrases, or occasionally with nouns or noun phrases.
> 
> Nouns and noun phrases should be used rarely and they might indicate that the type should be an abstract class, and not an interface.

File: src/Archive/ReadOnlyZipArchiveFolder.cs (hunk 2 above)
Comment (Arlodotexe) [reply src/Archive/ReadOnlyZipArchiveFolder.cs:146]: Because task cancellation isn't designed to work like that. When cancellation happens, it's handled by catching a `OperationCanceledException`. That way, every method in the call stack has the ability to add more long-running requests, and it can be canceled by anyone in the call stack, at any stage. 

In a language like C#, "safe returns" (such as a nullable value), should only be used if it's part of the contract, and it's extremely clear what the value means. Maybe there'd be a case for a nullable return value instead of throwing `FileNotFoundException`, but not for task cancellation.

See [Task Cancellation @ Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/standard/parallel-programming/task-cancellation) for official recommendations, and [this guide from dotnettutorials](https://dotnettutorials.net/lesson/how-to-cancel-a-task-in-csharp/) for a decent breakdown of how it works.

File: src/Archive/ZipArchiveFolder.cs (hunk 3 above)
Comment (Arlodotexe) [reply src/Archive/ZipArchiveFolder.cs:113]: That wasn't the point of this PR, but that's a good question. Mind checking? Can open a new ticket for later, if so.

File: src/Archive/ZipArchiveFolder.cs (hunk 4 above)
Comment (Arlodotexe) [reply src/Archive/ZipArchiveFolder.cs]: Good catch! Fixed 🙂

File: src/Extensions/CopyAndMoveExtensions.cs (hunk 5 above)
Comment (Arlodotexe) [reply src/Extensions/CopyAndMoveExtensions.cs:23]: `IFastFileCopy<T>` means it can do a fast file copy for the provided type. Faster than we can do, manually.

File: src/Extensions/CopyAndMoveExtensions.cs (hunk 6 above)
Comment (Arlodotexe) [reply src/Extensions/CopyAndMoveExtensions.cs:41]: See above comments about exception handling

File: src/Extensions/CopyAndMoveExtensions.cs (hunk 7 above)
Comment (Arlodotexe) [reply src/Extensions/CopyAndMoveExtensions.cs:63]: See above comments about exception handling. It's the same reason task cancellation works so well via throwing.

File: src/Extensions/GetFilesAndFoldersExtensions.cs (hunk 8 above)
Comment (Arlodotexe) [reply src/Extensions/GetFilesAndFoldersExtensions.cs:18]: I'm not sure why you would want to do this. Can you explain more?

File: src/Extensions/GetFilesAndFoldersExtensions.cs (hunk 9 above)
Comment (Arlodotexe) [reply src/Extensions/GetFilesAndFoldersExtensions.cs:26]: If there are no items then t

File: src/Extensions/GetFirstByNameExtension.cs (hunk 10 above)
Comment (Arlodotexe) [reply src/Extensions/GetFirstByNameExtension.cs:19]: Had that and it was too long. This is much shorter, especially noticeable on the interfaces. (Using `IFastGetFirstByName` instead of `IFastGetFirstItemByName`). I think it still gets the point across.

@yoshiask What are your thoughts here?

File: src/Extensions/GetItemByRelativePathExtension.cs (hunk 11 above)
Comment (Arlodotexe) [reply src/Extensions/GetItemByRelativePathExtension.cs:28]: This one donated from Strix Music 😎
Glad you like it!

File: src/Extensions/GetRelativePathToExtension.cs (hunk 12 above)
Comment (Arlodotexe) [reply src/Extensions/GetRelativePathToExtension.cs:27]: `to` and `from` aren't reserved keywords, though `from` is a contextual keyword. It means we can use them as variable names in C#.

File: src/HttpFile.cs (hunk 13 above)
Comment (Arlodotexe) [reply src/HttpFile.cs:25]: It's completely normal to be instantiating things in the constructor. How else would you set up a class for use? 🙂

The MessageHandler here is the default, because it's required for our class to function. It can be overridden like any other property.

File: src/Memory/MemoryFolder.cs (hunk 14 above)
Comment (Arlodotexe) [reply src/Memory/MemoryFolder.cs:156]: MemoryFolder isn't holding any memory that need to be disposed.

It does contain a reference to a `MemoryFolderWatcher`, but disposing that class doesn't do anything. It will get cleaned up normally by the GC, so the consumer doesn't need to dispose it manually.

File: src/SystemIO/SystemFolder.cs (hunk 15 above)
Comment (Arlodotexe) [reply src/SystemIO/SystemFolder.cs:40]: For cases like this - where you take a random data and assume it's a working file - it's _highly_ recommended to do a synchronous check like this (if you can) to make sure it actually exists before working with it.

That goes for all implementations of OwlCore.Storage. If it's not possible or the call is too heavy, don't do it. Otherwise, _do it_.

Object instances like this can be passed around for quite a while before any problems start manifesting if you gave it a bad path, and it makes debugging problems with _your_ code that much harder.

File: src/SystemIO/SystemFolder.cs (hunk 16 above)
Comment (Arlodotexe) [reply src/SystemIO/SystemFolder.cs:41]: Constructors are just fancy synchronous method calls, there's nothing wrong with throwing in the constructor if some bad data was provided and can't be used.

See above comment(s).

File: src/SystemIO/SystemFolder.cs (hunk 17 above)
Comment (Arlodotexe) [reply src/SystemIO/SystemFolder.cs:44]: Constructors are just fancy synchronous method calls, there's nothing wrong with throwing in the constructor if some bad data was provided and can't be used.

See above comment(s).

File: src/SystemIO/SystemFolder.cs (hunk 18 above)
Comment (Arlodotexe) [reply src/SystemIO/SystemFolder.cs:114]: It's expected that the provided ID is an ancestor of the current folder, and can always be found if you crawl the object graph for it. The phrasing here reflects that.

File: src/SystemIO/SystemFolder.cs (hunk 19 above)
Comment (Arlodotexe) [reply src/SystemIO/SystemFolder.cs:180]: Not for System.IO, see [here](https://stackoverflow.com/questions/29013958/how-to-implement-an-async-file-delete-create-move).

File: src/SystemIO/SystemFolder.cs (hunk 20 above)
Comment (Arlodotexe) [reply src/SystemIO/SystemFolder.cs:202]: There's no need to catch and rethrow the exception here. It can be done by the consumer if that's what they want.

File: src/SystemIO/SystemFolder.cs (hunk 21 above)
Comment (Arlodotexe) [reply src/SystemIO/SystemFolder.cs:218]: There's no need to catch and rethrow the exception here. It can be done by the consumer if that's what they want.

File: src/HttpFile.cs (hunk 13 above)
Comment (Arlodotexe) [reply src/HttpFile.cs:25]: 🙂 It's completely normal to be instantiating things in the constructor. How else could you set up a class for use without overloading the consumer?

The MessageHandler here has a default value of `HttpClientHandler`, because it's required for our class to function. It can be reassigned by the consumer like any other property.

That said, I reviewed the file again and it looks like I didn't add the setter for the property. You found some unfinished changes. I've added an init-only setter, and moved the default value to the property itself, instead of the constructor.

File: src/Archive/ReadOnlyZipArchiveFolder.cs (hunk 2 above)
Comment (amaid) [reply src/Archive/ReadOnlyZipArchiveFolder.cs:146]: Understood.

File: src/Extensions/GetFilesAndFoldersExtensions.cs (hunk 8 above)
Comment (amaid) [reply src/Extensions/GetFilesAndFoldersExtensions.cs:18]: Something like:
`
var result = folder.GetItemsAsync(StorableType.File, cancellationToken);
if(!result.Any()){
 // return default or empty list of IChildFile instead of casting that can be expensive
}
return folder.GetItemsAsync(StorableType.File, cancellationToken).Cast<IChildFile>();;
`

File: src/Extensions/GetFilesAndFoldersExtensions.cs (hunk 9 above)
Comment (amaid) [reply src/Extensions/GetFilesAndFoldersExtensions.cs:26]: Something like:
```csharp
var result = await folder.GetItemsAsync(StorableType.File, cancellationToken);
if(!result.Any()){
 // return default or empty list of IChildFile instead of casting that can be expensive
}
return folder.GetItemsAsync(StorableType.File, cancellationToken).Cast<IChildFile>();

File: src/Memory/MemoryFolder.cs (hunk 14 above)
Comment (amaid) [reply src/Memory/MemoryFolder.cs:156]: Makes sense.

File: src/SystemIO/SystemFolder.cs (hunk 20 above)
Comment (amaid) [reply src/SystemIO/SystemFolder.cs:202]: Ahh this makes sense

File: src/SystemIO/SystemFolder.cs (hunk 21 above)
Comment (amaid) [reply src/SystemIO/SystemFolder.cs:218]: Ahh this makes sense

**Review by amaid — APPROVED** [review]

File: src/Extensions/GetFilesAndFoldersExtensions.cs (hunk 8 above)
Comment (Arlodotexe) [reply src/Extensions/GetFilesAndFoldersExtensions.cs:18]: This adds complexity, creates a new async state machine that isn't needed, and doesn't change the behavior. Changing the number of items doesn't change the performance, because it's just a type cast. It would need to be _enumerated_ for the number of items to have an effect on performance, which we aren't doing here.

The call to `.Cast<T>` is negligible, we're going to keep it as-is.

File: src/Extensions/GetFilesAndFoldersExtensions.cs (hunk 9 above)
Comment (Arlodotexe) [reply src/Extensions/GetFilesAndFoldersExtensions.cs:26]: See other thread - https://github.com/Arlodotexe/OwlCore.Storage/pull/19#discussion_r1111293865

File: src/Archive/ZipArchiveFolder.cs (hunk 3 above)
Comment (yoshiask) [reply src/Archive/ZipArchiveFolder.cs]: No, `ZipArchive` does not have any asynchronous methods.

File: src/Extensions/GetFirstByNameExtension.cs (hunk 10 above)
Comment (yoshiask) [reply src/Extensions/GetFirstByNameExtension.cs:19]: I agree that `GetFirstItemByName` is technically more descriptive, I also agree the interface name is already descriptive and long enough. On the off chance that someone doesn't know or isn't sure what the extension does just from the name, they can just read the XML doc summary.
